---
# file: roles/ilo/tasks/collect.yml
- name: Getting Ironic node list
  command:
    openstack {{ ilo_ironic_options }} baremetal node list -c UUID -f value
  register: ironic_nodes

- name: Getting iLO address
  shell:
    openstack {{ ilo_ironic_options }} baremetal node show {{ item }} \
      --fields driver_info \
      -f json | jq -r .driver_info.ipmi_address
  with_items: "{{ ironic_nodes.stdout_lines }}"
  when: ironic_nodes is defined
  register: ironic_nodes_ilo_address

- name: Getting Ironic node name
  shell:
    openstack {{ ilo_ironic_options }} baremetal node show {{ item }} \
      --fields name \
      -f json | jq -r .name
  with_items: "{{ ironic_nodes.stdout_lines }}"
  when: ironic_nodes is defined
  register: ironic_nodes_name
