---
# file: roles/ilo/tasks/ilo.yml
- name: Set iLO hostname
  uri:
    url: "https://{{ item.0.stdout }}/rest/v1/managers/1/networkservice"
    method: PATCH
    user: "{{ ilo_user }}"
    password: "{{ ilo_password }}"
    force_basic_auth: true
    validate_certs: false
    body: '{"HostName":"{{ item.1.stdout }}"}'
    body_format: json
    status_code: 200
  with_together:
    - "{{ ironic_nodes_ilo_address.results }}"
    - "{{ ironic_nodes_name.results }}"

- name: Set iLO server name
  uri:
    url: "https://{{ item.0.stdout }}/rest/v1/systems/1/bios/settings"
    method: PATCH
    user: "{{ ilo_user }}"
    password: "{{ ilo_password }}"
    force_basic_auth: true
    validate_certs: false
    body: '{"ServerName": "{{ item.1.stdout }}"}'
    body_format: json
    status_code: 200
  with_together:
    - "{{ ironic_nodes_ilo_address.results }}"
    - "{{ ironic_nodes_name.results }}"

- name: Set iLO oemhp_server_name via SSH
  command:
    sshpass -p {{ ilo_password }} ssh {{ ilo_ssh_opts }} {{ item.0.stdout }} -l {{ ilo_user }} 'set /system1 oemhp_server_name="{{ item.1.stdout }}.{{ ilo_fqdn }}"'
  with_together:
    - "{{ ironic_nodes_ilo_address.results }}"
    - "{{ ironic_nodes_name.results }}"
