---
# file: roles/ilo/tasks/main.yml
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - ilo
    - ilo-prepare
    - ilo-collect
    - ilo-bios
    - ilo-ilo
    - ilo-firmware
    - ilo-power
    - ilo-mac

- name: Include Bifrost inventory file
  include_vars: "{{ ilo_inventory_file }}"
  tags:
    - ilo
    - ilo-prepare
    - ilo-collect
    - ilo-bios
    - ilo-ilo
    - ilo-firmware
    - ilo-power
    - ilo-mac

- set_fact:
    ipmi: "{% for k, v in item.items() %} {{- v.ipmi -}} {% endfor %}"
  with_items: "{{ inventory_nodes }}"
  register: ilo_addr
  tags:
    - ilo
    - ilo-prepare
    - ilo-collect
    - ilo-bios
    - ilo-ilo
    - ilo-firmware
    - ilo-power
    - ilo-mac

- include: bios.yml
  tags: [ ilo, ilo-bios, ilo-mac, ilo-firmware, ilo-power ]

- include: prepare.yml
  tags: [ ilo, ilo-prepare, ilo-mac ]

- include: collect.yml
  tags: [ ilo, ilo-collect, ilo-ilo ]
  when: ilo_collect is defined and
        ilo_collect | bool

- include: ilo.yml
  tags: [ ilo, ilo-ilo ]
  when: ilo_collect is defined and
        ilo_collect | bool and
        ironic_nodes_ilo_address is defined and
        ironic_nodes_name is defined

- include: firmware.yml
  tags: [ ilo, ilo-firmware ]
  when: ilo_update_firmware is defined and
        ilo_update_firmware | bool

- include: power.yml
  tags: [ ilo, ilo-power ]
  when: ilo_power_reset is defined and
        ilo_power_reset | bool

- include: mac.yml
  tags: [ ilo, ilo-mac ]
  when: ilo_mac is defined and
        ilo_mac | bool
